version: "2"
services:
  store1:
    container_name: store1
    restart: always
    environment:
      - FLASK_APP=main.py
    build: . 
    image: tp6m35p4/modbus_microservices:lastest
    volumes:
      - ./store1:/app/configs
    ports:
      - "5000:5000"

  store2:
    container_name: store2
    image: tp6m35p4/modbus_microservices:lastest
    restart: always
    environment:
      - FLASK_APP=main.py
    volumes:
      - ./store2:/app/configs
    ports:
      - "5002:5000"

  agv:
    container_name: agv
    image: tp6m35p4/modbus_microservices:lastest
    restart: always
    environment:
      - FLASK_APP=main.py
    volumes:
      - ./agv:/app/configs
    ports:
      - "5001:5000"



